import DataTable from "@/components/custom/data-table/data-table";
import BaseLayout from "@/components/layout/base-layout";
import { blockedAsnColumns } from "./components/blocked-asn-data-table/blocked-asn-columns";
import type { BlockedAsnType } from "./types/blocked-asn-type";
import { BlockedAsnToolbar } from "./components/blocked-asn-data-table/blocked-asn-toolbar";

const blockedAsns: BlockedAsnType[] = [
    {
        id: '1',
        asn: 456457,
        asnName: 'Example ASN 1',
        asnOrg: 'Example Organization',
        scope: 'global',
        serviceName: 'auth-service',
        accountId: 'ACC-001',
        reason: 'Multiple failed login attempts detected',
        reasonNotes: 'Numerous failed login attempts observed from this ASN over the past 24 hours.',
        blockType: 'temporary',
        severity: 3,
        blockedAt: '2025-12-27T14:30:00Z',
        expiresAt: '2025-12-28T14:30:00Z',
        createdBy: 'system',
        lastHitAt: '2025-12-27T16:45:00Z',
        hitCount: 127,
    },
    {
        id: '2',
        asn: 980890,
        asnName: 'Example ASN 1',
        asnOrg: 'Resource Organization',
        scope: 'service',
        serviceName: 'api-gateway',
        accountId: 'ACC-002',
        reason: 'Suspicious API scraping activity',
        reasonNotes: 'Detected high volume of API requests indicative of data scraping behavior.',
        blockType: 'permanent',
        severity: 5,
        blockedAt: '2025-12-20T09:15:00Z',
        expiresAt: '',
        createdBy: 'admin@company.com',
        lastHitAt: '2025-12-28T08:12:00Z',
        hitCount: 2341,
    },
    {
        id: '3',
        asn: 345,
        asnName: 'Example ASN 2',
        asnOrg: 'RJ Organization',
        scope: 'global',
        serviceName: 'payment-service',
        accountId: 'ACC-003',
        reason: 'Known malicious actor - fraud attempts',
        reasonNotes: 'This ASN has been linked to multiple fraud attempts in recent investigations.',
        blockType: 'permanent',
        severity: 5,
        blockedAt: '2025-11-15T22:00:00Z',
        expiresAt: '',
        createdBy: 'security-team',
        lastHitAt: '2025-12-25T03:22:00Z',
        hitCount: 89,
    },
    {
        id: '4',
        asn: 675,
        asnName: 'Example ASN 2',
        asnOrg: 'Monitor Organization',
        scope: 'account',
        serviceName: 'user-service',
        accountId: 'ACC-004',
        reason: 'DDoS attack source',
        blockType: 'temporary',
        severity: 4,
        blockedAt: '2025-12-26T11:00:00Z',
        expiresAt: '2025-12-29T11:00:00Z',
        createdBy: 'auto-defense',
        lastHitAt: '2025-12-26T11:45:00Z',
        hitCount: 15420,
        reasonNotes: 'This ASN has been identified as a source of DDoS attacks targeting multiple services.',
    },
    {
        id: '5',
        asn: 2312,
        asnName: 'Example ASN 3',
        asnOrg: 'Hockey Organization',
        scope: 'service',
        serviceName: 'auth-service',
        accountId: 'ACC-005',
        reason: 'Brute force password attack',
        blockType: 'temporary',
        severity: 4,
        blockedAt: '2025-12-28T02:30:00Z',
        expiresAt: '2025-12-29T02:30:00Z',
        createdBy: 'system',
        lastHitAt: '2025-12-28T02:28:00Z',
        hitCount: 543,
        reasonNotes: 'Numerous brute force password attempts detected from this ASN targeting user accounts.',
    },
    {
        id: '6',
        asn: 123,
        asnName: 'Example ASN 3',
        asnOrg: 'Keyboard Organization',
        scope: 'global',
        serviceName: 'inventory-service',
        accountId: 'ACC-006',
        reason: 'SQL injection attempts',
        blockType: 'permanent',
        severity: 5,
        blockedAt: '2025-12-10T18:20:00Z',
        expiresAt: '',
        createdBy: 'waf-system',
        lastHitAt: '2025-12-27T09:10:00Z',
        hitCount: 312,
        reasonNotes: 'Multiple SQL injection attempts have been detected originating from this ASN.',
    },
    {
        id: '7',
        asn: 8789,
        asnName: 'Example ASN 4',
        asnOrg: 'Subway Organization',
        scope: 'global',
        serviceName: 'all',
        accountId: '',
        reason: 'Tor exit node - policy violation',
        blockType: 'permanent',
        severity: 2,
        blockedAt: '2025-10-01T00:00:00Z',
        expiresAt: '',
        createdBy: 'policy-engine',
        lastHitAt: '2025-12-28T07:55:00Z',
        hitCount: 8923,
        reasonNotes: 'This ASN is known to operate Tor exit nodes, violating our access policies.',
    },
    {
        id: '8',
        asn: 799,
        asnName: 'Example ASN 4',
        asnOrg: 'HR Organization',
        scope: 'account',
        serviceName: 'billing-service',
        accountId: 'ACC-008',
        reason: 'Credential stuffing detected',
        blockType: 'temporary',
        severity: 3,
        blockedAt: '2025-12-27T20:15:00Z',
        expiresAt: '2025-12-30T20:15:00Z',
        createdBy: 'system',
        lastHitAt: '2025-12-27T20:14:00Z',
        hitCount: 78,
        reasonNotes: 'Numerous credential stuffing attempts have been observed from this ASN targeting billing services.',
    },
    {
        id: '9',
        asn: 8943,
        asnName: 'Example ASN 5',
        asnOrg: 'Billables Organization',
        scope: 'account',
        serviceName: 'billing-service',
        accountId: 'ACC-008',
        reason: 'Credential stuffing detected',
        blockType: 'temporary',
        severity: 3,
        blockedAt: '2025-12-27T20:15:00Z',
        expiresAt: '2025-12-30T20:15:00Z',
        createdBy: 'system',
        lastHitAt: '2025-12-27T20:14:00Z',
        hitCount: 78,
        reasonNotes: 'Numerous credential stuffing attempts have been observed from this ASN targeting billing services.',
    },
    {
        id: '10',
        asn: 456457,
        asnName: 'Example ASN 5',
        asnOrg: 'Marketing Organization',
        scope: 'account',
        serviceName: 'billing-service',
        accountId: 'ACC-008',
        reason: 'Credential stuffing detected',
        blockType: 'temporary',
        severity: 3,
        blockedAt: '2025-12-27T20:15:00Z',
        expiresAt: '2025-12-30T20:15:00Z',
        createdBy: 'system',
        lastHitAt: '2025-12-27T20:14:00Z',
        hitCount: 78,
        reasonNotes: 'Numerous credential stuffing attempts have been observed from this ASN targeting billing services.',
    },
    {
        id: '11',
        asn: 456457,
        asnName: 'Example ASN 5',
        asnOrg: 'Sales Organization',
        scope: 'account',
        serviceName: 'billing-service',
        accountId: 'ACC-008',
        reason: 'Credential stuffing detected',
        blockType: 'temporary',
        severity: 3,
        blockedAt: '2025-12-27T20:15:00Z',
        expiresAt: '2025-12-30T20:15:00Z',
        createdBy: 'system',
        lastHitAt: '2025-12-27T20:14:00Z',
        hitCount: 78,
        reasonNotes: 'Numerous credential stuffing attempts have been observed from this ASN targeting billing services.',
    },
];

export default function BlockedAsnPage() {
    return (
        <BaseLayout title="Blocked ASNs">
            <DataTable
                columns={blockedAsnColumns}
                data={blockedAsns}
                initialColumnVisibility={{ cidrRange: false, serviceName: false, hitCount: false, createdBy: false }}
                toolbar={(table, initialColumnVisibility, data) => <BlockedAsnToolbar table={table} initialColumnVisibility={initialColumnVisibility} data={data} />}
            />
        </BaseLayout>
    );
}